version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: your_database
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80" # Accède à phpMyAdmin via localhost:8080
    environment:
      PMA_HOST: db # Nom du service de la base de données
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword

volumes:
  db_data:
